### ISSUE TITLE
Less restrictive license

### ISSUE THREAD

**Issue by jj39** [asiryan/OpenJDK.BigMathNET#1]
This library looks pretty cool and could be very useful. Would you consider changing the license to something less restrictive so that it could be used in proprietary apps without having to make the app that uses it also GPL? As it stands now, if I use this library in an app, then that app must also be GPL and I have to open source that app, so this library cannot be used in any proprietary apps.

For example, [GPL Lesser LGPL](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License) would be sufficient to allow your library to be used in an app that isn't GPL as long as it is not a derivative work (ie. it statically links your dll and does not change it). Of course there are other even less restrictive licenses like MIT that would also work.

**Comment by asiryan** [comment]
Thanks so much for your feedback :)
I changed the license for MIT.
Please update the nuget package in your project.
